spring:
  application:
    name: gateway-service

  cloud:
    config:
      discovery:
        enable: true
        id-service: config-service

  security:
    oauth2:
      client:
        provider:
          microservicios:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
        registration:
          gateway-service:
            provider: microservicios
            client-id: microservicios
            client-secret: vk2JShO3N43msLTfmQ1Q5VEjow6QS0S2
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8050/login/oauth2/code/keycloak'


