server:
  port: 8031
  servlet:
    context-path: /bills/

spring:
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: sa
  h2:
    console:
      enabled: 'true'
      path: /h2-console

  application:
    name: bill-service

  security:
    oauth2:
      client:
        provider:
          microservicios:
            issuer-uri: http://localhost:8082/realms/DigitalMedia
        registration:
          gateway-service:
            provider: microservicios
            client-id: microservicios
            scope: openid, roles
            client-secret: vk2JShO3N43msLTfmQ1Q5VEjow6QS0S2
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8002/login/oauth2/code/keycloak'

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true

message: Hello from Bill Server

management:
  endpoints:
    web:
      exposure:
        include: '*'